<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EngrCAD.Viewer\EngrCAD.Viewer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bracket.params.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
