using EngrCAD.BRep;
using EngrCAD.Core;

namespace EngrCAD.Modeling;

/// <summary>
/// A cycloidal spur gear definition — the clock and instrument tooth form: module, tooth
/// count and the <b>generating (describing/rolling) circle</b>, which is what a cycloidal
/// system carries instead of a pressure angle.
/// </summary>
/// <remarks>
/// <para>
/// The flank <i>above</i> the pitch circle (the FACE) is an <b>epicycloid</b> — the trace of
/// a point on a circle of <see cref="GeneratingCircleRadius"/> rolling OUTSIDE the pitch
/// circle — and the flank <i>below</i> it is a <b>hypocycloid</b>, the same circle rolling
/// INSIDE. Both curves leave the pitch circle at a cusp whose tangent is exactly RADIAL, so
/// face and flank meet tangent-continuously there with nothing to arrange.
/// </para>
/// <para>
/// <b>Conjugacy is a property of the PAIR, not of one gear</b>: a wheel's epicycloidal face
/// works against a pinion's hypocycloidal flank only if both were generated by the SAME
/// describing circle. Sharing one generating circle across a set (the interchangeable-set
/// practice) satisfies that in both directions at once, which is why this type carries a
/// single generating circle and <see cref="CycloidalGears.Mesh"/> refuses a pair whose
/// circles differ. The classic clock choice is a generating circle whose DIAMETER is half
/// the pinion's pitch diameter — i.e. equal to the pinion's pitch RADIUS — because a
/// hypocycloid generated by a circle of half the pitch radius degenerates to a straight
/// RADIAL line, giving the pinion the radial leaves a clockmaker cuts
/// (<see cref="HasRadialFlanks"/>, <see cref="WithRadialFlanks"/>).
/// </para>
/// <para>
/// <b>The honest contrast with the involute</b>: an involute pair transmits a constant ratio
/// at ANY centre distance, because the ratio is set by the base circles rather than by the
/// mounting. A cycloidal pair does not — the describing circle must roll on BOTH pitch
/// circles, which pins the centre distance to <c>(d₁ + d₂)/2</c>. Mounted long or short, a
/// cycloidal pair still runs, but the instantaneous ratio ripples. That is a property of the
/// tooth form, not a defect of this factory, and it is measured rather than asserted in
/// <c>CycloidalGearTests</c>.
/// </para>
/// <para>
/// The proportion coefficients default to a modest general cycloidal practice (addendum
/// 0.60·m, dedendum 0.80·m, root fillet 0.15·m); <see cref="ClockGearProportions"/> supplies
/// the BS 978-2 horological table, which is a TRANSCRIPTION and carries the
/// verify-against-datasheet flag.
/// </para>
/// </remarks>
public sealed record CycloidalGearSpec
{
    public CycloidalGearSpec(double module, int teeth, double generatingCircleDiameter)
    {
        if (!(module > 0))
            throw new ArgumentOutOfRangeException(nameof(module), "Module must be positive.");
        if (teeth < 3)
            throw new ArgumentOutOfRangeException(nameof(teeth), "A gear needs at least 3 teeth.");
        if (!(generatingCircleDiameter > 0))
            throw new ArgumentOutOfRangeException(nameof(generatingCircleDiameter),
                "The generating (describing) circle diameter must be positive.");
        Module = module;
        Teeth = teeth;
        GeneratingCircleDiameter = generatingCircleDiameter;
    }

    /// <summary>Module m (mm) — pitch diameter over tooth count.</summary>
    public double Module { get; }

    /// <summary>Tooth count z (a pinion's teeth are traditionally called leaves).</summary>
    public int Teeth { get; }

    /// <summary>
    /// Diameter of the generating (describing, rolling) circle — the circle that rolls on
    /// the pitch circle to trace both cycloidal flanks. A cycloidal system's shape parameter,
    /// where an involute system has the pressure angle.
    /// </summary>
    public double GeneratingCircleDiameter { get; }

    /// <summary>Addendum coefficient h_a* (of module).</summary>
    public double AddendumCoefficient { get; init; } = 0.60;

    /// <summary>Dedendum coefficient h_f* (of module), including the clearance.</summary>
    public double DedendumCoefficient { get; init; } = 0.80;

    /// <summary>Root fillet radius coefficient ρ_f* (of module); 0 leaves a sharp root corner.</summary>
    public double RootFilletCoefficient { get; init; } = 0.15;

    /// <summary>
    /// Circumferential backlash allowance (mm) taken off the tooth thickness at the pitch
    /// circle, half from each flank. Removing thickness ROTATES each flank about the gear
    /// centre, and a cycloid rotated about its own pitch circle's centre is the same cycloid
    /// at another phase — so backlash costs nothing in conjugacy on the driving flank.
    /// </summary>
    public double BacklashAllowance { get; init; }

    /// <summary>Pitch (reference) diameter d = m·z.</summary>
    public double PitchDiameter => Module * Teeth;

    /// <summary>Pitch radius r = m·z/2.</summary>
    public double PitchRadius => Module * Teeth / 2;

    /// <summary>Circular pitch p = π·m.</summary>
    public double CircularPitch => Math.PI * Module;

    /// <summary>Radius of the generating circle, ρ.</summary>
    public double GeneratingCircleRadius => GeneratingCircleDiameter / 2;

    /// <summary>Tip (addendum) diameter d_a = m·(z + 2·h_a*).</summary>
    public double TipDiameter => Module * (Teeth + 2 * AddendumCoefficient);

    /// <summary>Root diameter d_f = m·(z − 2·h_f*).</summary>
    public double RootDiameter => Module * (Teeth - 2 * DedendumCoefficient);

    /// <summary>Tooth thickness along the pitch circle, s = π·m/2 − backlash.</summary>
    public double ToothThicknessAtPitch => Math.PI * Module / 2 - BacklashAllowance;

    /// <summary>Half the angular tooth thickness at the pitch circle, ψ = s/(2r).</summary>
    public double HalfToothAngle => ToothThicknessAtPitch / (2 * PitchRadius);

    /// <summary>
    /// The generating circle DIAMETER that makes this gear's hypocycloidal flanks exactly
    /// radial: ρ = r/2, i.e. a describing circle of diameter equal to the pitch RADIUS.
    /// </summary>
    public double RadialFlankGeneratingDiameter => PitchRadius;

    /// <summary>Whether the flanks are the straight radial lines of the ρ = r/2 identity
    /// (a relative test — the identity is exact, so the band only absorbs arithmetic).</summary>
    public bool HasRadialFlanks =>
        Math.Abs(GeneratingCircleDiameter - RadialFlankGeneratingDiameter) <= 1e-12 * PitchDiameter;

    /// <summary>
    /// The greatest addendum this generating circle can trace: an epicycloid reaches
    /// r + 2ρ and no further, so an addendum past 2ρ has no face to draw. The cycloidal
    /// counterpart of the involute's tip-past-the-base-circle limit.
    /// </summary>
    public double MaximumAddendum => 2 * GeneratingCircleRadius;

    /// <summary>The smallest radius a hypocycloidal flank reaches, |r − 2ρ| — zero exactly
    /// when the flanks are radial, since a radial flank runs to the centre.</summary>
    public double DeepestFlankRadius => Math.Abs(PitchRadius - 2 * GeneratingCircleRadius);

    /// <summary>
    /// A gear whose flanks are exactly radial: the generating circle diameter is set to the
    /// pitch radius. Mesh it with a wheel that shares the same generating circle.
    /// </summary>
    public static CycloidalGearSpec WithRadialFlanks(double module, int teeth) =>
        new(module, teeth, module * teeth / 2);
}

/// <summary>
/// A conjugate cycloidal pair: two gears that share one generating circle, and so satisfy
/// the law of gearing in both directions (wheel face against pinion flank, and pinion face
/// against wheel flank).
/// </summary>
public sealed record CycloidalMesh(CycloidalGearSpec Pinion, CycloidalGearSpec Wheel)
{
    /// <summary>The design centre distance (d₁ + d₂)/2. Unlike an involute pair, a cycloidal
    /// pair transmits a constant ratio only here.</summary>
    public double CentreDistance => (Pinion.PitchDiameter + Wheel.PitchDiameter) / 2;

    /// <summary>Speed reduction z_wheel / z_pinion.</summary>
    public double GearRatio => (double)Wheel.Teeth / Pinion.Teeth;

    /// <summary>The generating circle both members are cut with.</summary>
    public double GeneratingCircleDiameter => Pinion.GeneratingCircleDiameter;
}

/// <summary>
/// A generated cycloidal tooth profile: the <see cref="Sketch"/> (lines and circular arcs
/// only, so a cycloidal gear is exact in all three representations downstream) plus the fit
/// contract — the tolerance that was asked for and the deviation that was measured.
/// </summary>
public sealed class CycloidalProfile
{
    internal CycloidalProfile(CycloidalGearSpec spec, Sketch sketch, double fitTolerance,
        double maxFitDeviation, int curvesPerFace, int curvesPerFlank, double closedFormArea,
        in CycloidalToothGeometry geometry)
    {
        Spec = spec;
        Sketch = sketch;
        FitTolerance = fitTolerance;
        MaxFitDeviation = maxFitDeviation;
        CurvesPerFace = curvesPerFace;
        CurvesPerFlank = curvesPerFlank;
        ClosedFormArea = closedFormArea;
        Geometry = geometry;
    }

    /// <summary>The definition this profile was generated from.</summary>
    public CycloidalGearSpec Spec { get; }

    /// <summary>The tooth profile as a closed sketch (CCW outer loop, no holes), centred at
    /// the origin with one tooth centred on +X.</summary>
    public Sketch Sketch { get; }

    /// <summary>The flank fit tolerance that was requested (mm).</summary>
    public double FitTolerance { get; }

    /// <summary>The measured maximum deviation of the fitted epicycloid/hypocycloid from the
    /// closed form (mm) — at most <see cref="FitTolerance"/>. Everything else in the outline
    /// (tip arc, root arc, root fillets) is exact by construction, so this is the profile's
    /// entire error.</summary>
    public double MaxFitDeviation { get; }

    /// <summary>Curves the biarc chain spent on one epicycloidal face.</summary>
    public int CurvesPerFace { get; }

    /// <summary>Curves the biarc chain spent on one hypocycloidal flank (2 collinear straight
    /// segments when the flank is radial — the ρ = r/2 identity, which the fit reaches on its
    /// own rather than by a special case).</summary>
    public int CurvesPerFlank { get; }

    /// <summary>
    /// The EXACT area of the ideal (un-fitted) outline, from closed forms. Both cycloid
    /// families integrate in closed form under Green's theorem: the epicycloid contributes
    /// ½(r+ρ)(r+2ρ)[t − (ρ/r)·sin(rt/ρ)] and the hypocycloid ½(r−ρ)(r−2ρ)[…] — note the
    /// second REDUCES to exactly zero at ρ = r/2, which is the radial-flank identity showing
    /// up in the area (a line through the origin encloses nothing).
    /// </summary>
    public double ClosedFormArea { get; }

    /// <summary>Construction values for verification (internal test seam).</summary>
    internal CycloidalToothGeometry Geometry { get; }
}

/// <summary>Closed-form construction values for one canonical cycloidal tooth (internal test seam).</summary>
internal readonly record struct CycloidalToothGeometry(
    double PitchRadius, double GeneratingRadius, double TipRadius, double RootRadius,
    double FilletRadius, double HalfToothAngle, double FlankOrigin,
    double FaceRoll, double FlankRoll, double TipArcSweep, double RootArcSweep);

/// <summary>
/// Cycloidal gear factory: <see cref="Spur"/> generates the tooth profile as a
/// <see cref="Sketch"/>, <see cref="SpurGear"/> wraps it into a solid, and
/// <see cref="Mesh"/> builds (and checks) a conjugate pair.
/// </summary>
public static class CycloidalGears
{
    /// <summary>
    /// A conjugate cycloidal pair sharing one generating circle. Omitting
    /// <paramref name="generatingCircleDiameter"/> takes the classic clock choice — half the
    /// PINION's pitch diameter, which makes the pinion's leaves exactly radial.
    /// </summary>
    public static CycloidalMesh Pair(double module, int pinionTeeth, int wheelTeeth,
        double? generatingCircleDiameter = null)
    {
        double generating = generatingCircleDiameter ?? module * pinionTeeth / 2;
        return new CycloidalMesh(
            new CycloidalGearSpec(module, pinionTeeth, generating),
            new CycloidalGearSpec(module, wheelTeeth, generating));
    }

    /// <summary>
    /// Checks that two gears are conjugate and returns them as a <see cref="CycloidalMesh"/>.
    /// The condition IS that the two share a generating circle (a wheel's epicycloidal face
    /// rolls against a pinion's hypocycloidal flank only when one circle traced both) and
    /// that the modules match; a mismatch is refused by name rather than drawn.
    /// </summary>
    public static CycloidalMesh Mesh(CycloidalGearSpec pinion, CycloidalGearSpec wheel)
    {
        ArgumentNullException.ThrowIfNull(pinion);
        ArgumentNullException.ThrowIfNull(wheel);
        if (Math.Abs(pinion.Module - wheel.Module) > 1e-12 * pinion.Module)
            throw new ArgumentException(
                $"Cycloidal gears mesh only at a common module: {pinion.Module:0.####} and "
                + $"{wheel.Module:0.####}.", nameof(wheel));
        double d1 = pinion.GeneratingCircleDiameter, d2 = wheel.GeneratingCircleDiameter;
        if (Math.Abs(d1 - d2) > 1e-9 * Math.Max(d1, d2))
            throw new ArgumentException(
                $"Cycloidal gears are conjugate only when one describing circle traced both: "
                + $"the pinion's is {d1:0.####} and the wheel's {d2:0.####}. A wheel's "
                + "epicycloidal face rolls against a pinion's hypocycloidal flank, so the two "
                + "must have been generated by the SAME circle.", nameof(wheel));
        return new CycloidalMesh(pinion, wheel);
    }

    /// <summary>
    /// Generates the cycloidal spur gear profile for <paramref name="spec"/> as a closed
    /// <see cref="Sketch"/> centred at the origin with a tooth centred on +X.
    /// </summary>
    /// <param name="spec">Module, tooth count, generating circle and the proportion coefficients.</param>
    /// <param name="fitTolerance">Maximum allowed deviation of the fitted flanks from the
    /// closed-form cycloids (mm). Defaults to module·1e-4 — an order tighter than the finest
    /// instrument-gear profile tolerances. The deviation actually achieved is reported on
    /// <see cref="CycloidalProfile.MaxFitDeviation"/>.</param>
    /// <exception cref="ArgumentException">
    /// Refused by name rather than drawn: a generating circle past half the pitch radius (the
    /// hypocycloid then curls the wrong way and UNDERCUTS the flank — the cycloidal
    /// counterpart of the involute's z_min limit), an addendum past the 2ρ an epicycloid can
    /// reach, a dedendum past the |r − 2ρ| a hypocycloid can reach, pointed teeth, a root
    /// fillet that does not fit its gap or that reaches the pitch circle, and degenerate radii.
    /// </exception>
    public static CycloidalProfile Spur(CycloidalGearSpec spec, double? fitTolerance = null)
    {
        ArgumentNullException.ThrowIfNull(spec);
        double tolerance = fitTolerance ?? spec.Module * 1e-4;
        if (!(tolerance > 0))
            throw new ArgumentOutOfRangeException(nameof(fitTolerance));
        if (!(spec.AddendumCoefficient > 0))
            throw new ArgumentException("Addendum coefficient must be positive.", nameof(spec));
        if (!(spec.DedendumCoefficient > 0))
            throw new ArgumentException("Dedendum coefficient must be positive.", nameof(spec));
        if (spec.RootFilletCoefficient < 0)
            throw new ArgumentException("Root fillet coefficient cannot be negative.", nameof(spec));

        double m = spec.Module;
        int z = spec.Teeth;
        double r = spec.PitchRadius;
        double rho = spec.GeneratingCircleRadius;
        double ra = r + m * spec.AddendumCoefficient;
        double rf = r - m * spec.DedendumCoefficient;
        double fillet = m * spec.RootFilletCoefficient;
        double psi = spec.HalfToothAngle;

        // Undercut: past ρ = r/2 the hypocycloid's cusp curls toward the tooth centre and the
        // flank necks below the pitch circle. Refused rather than drawn, the way the involute
        // factory refuses a rack-undercut tooth count - an honest refusal beats an
        // unverified flank.
        if (rho > r / 2 + 1e-12 * r)
            throw new ArgumentException(
                $"A generating circle of radius {rho:0.####} exceeds half the pitch radius "
                + $"({r / 2:0.####}), so the hypocycloidal flank curls back on itself and "
                + $"undercuts. Use at most a diameter of {spec.RadialFlankGeneratingDiameter:0.####} "
                + "(which makes the flank exactly radial), or add teeth.", nameof(spec));
        if (!(psi > 0))
            throw new ArgumentException(
                $"The backlash allowance {spec.BacklashAllowance:0.####} consumes the whole tooth "
                + $"thickness {Math.PI * m / 2:0.####}.", nameof(spec));
        if (!(rf > 0))
            throw new ArgumentException(
                $"Root diameter {2 * rf:0.###} is not positive (dedendum "
                + $"{spec.DedendumCoefficient}*m exceeds the pitch radius).", nameof(spec));
        if (ra > r + 2 * rho + 1e-12 * r)
            throw new ArgumentException(
                $"The addendum {m * spec.AddendumCoefficient:0.####} exceeds the "
                + $"{spec.MaximumAddendum:0.####} an epicycloid of this generating circle can "
                + "reach (a rolling circle of radius rho traces no further than r + 2*rho). "
                + "Reduce the addendum or enlarge the generating circle.", nameof(spec));
        if (rf < r - 2 * rho - 1e-12 * r)
            throw new ArgumentException(
                $"The root radius {rf:0.####} is deeper than the {spec.DeepestFlankRadius:0.####} "
                + "a hypocycloid of this generating circle reaches. Reduce the dedendum or "
                + "enlarge the generating circle.", nameof(spec));

        // Roll angles at the tip and the root, both CLOSED FORM: |E(t)|^2 and |H(t)|^2 each
        // reduce to a single cosine of r*t/rho, so the parameter at a stated radius inverts
        // with one arccos and no search.
        double tTip = (rho / r) * Math.Acos(Clamp(((r + rho) * (r + rho) + rho * rho - ra * ra)
            / (2 * rho * (r + rho))));
        double tRoot = (rho / r) * Math.Acos(Clamp((rf * rf - (r - rho) * (r - rho) - rho * rho)
            / (2 * rho * (r - rho))));

        double theta0 = -psi;   // the right flank crosses the pitch circle here

        Vector2d Face(double t) => FacePoint(r, rho, theta0, t);
        Vector2d FaceT(double t) => FaceTangent(r, rho, theta0, t);
        Vector2d Flank(double t) => FlankPoint(r, rho, theta0, t);
        Vector2d FlankT(double t) => FlankTangent(r, rho, theta0, t);

        // Root fillet: tangent to the flank and to the root circle. The tangency has no
        // closed form here (an involute's does), so it is a ROOT SOLVE on
        // g(t) = |H(t) + rho_f*n(t)| - (r_f + rho_f), bracketed by a scan - and the bracket
        // always exists, since g(0) > 0 for any fillet smaller than the flank's own depth and
        // g(t_root) < 0 because the fillet centre there is r_f + rho_f from the origin only
        // if the flank normal is exactly radial, which it is not.
        double tLow = tRoot;
        Vector2d filletCentre = default, filletRootPoint = default, filletFlankPoint = default;
        double filletSweep = 0;
        Arc2d? filletArc = null;
        if (fillet > 1e-9)   // weld tier: a fillet below weld tolerance is no segment at all
        {
            double Gap(double t)
            {
                var centre = Flank(t) + FilletNormal(r, rho, theta0, t) * fillet;
                return centre.Length - (rf + fillet);
            }
            if (!(Gap(0) > 0))
                throw new ArgumentException(
                    $"The root fillet (rho_f = {spec.RootFilletCoefficient}*m = {fillet:0.####}) is "
                    + "larger than the flank it must be tangent to. Reduce the fillet coefficient "
                    + "or deepen the dedendum.", nameof(spec));
            double lo = 0, hi = double.NaN;
            const int scan = 512;
            for (int i = 1; i <= scan; i++)
            {
                double t = tRoot * i / scan;
                if (Gap(t) <= 0) { hi = t; break; }
                lo = t;
            }
            if (double.IsNaN(hi))
                throw new ArgumentException(
                    $"The root fillet (rho_f = {fillet:0.####}) never becomes tangent to both the "
                    + "flank and the root circle. Reduce the fillet coefficient.", nameof(spec));
            for (int i = 0; i < 100; i++)
            {
                double mid = (lo + hi) / 2;
                if (Gap(mid) > 0) lo = mid; else hi = mid;
            }
            tLow = (lo + hi) / 2;
            filletFlankPoint = Flank(tLow);
            if (r - filletFlankPoint.Length < 1e-6 * r)
                throw new ArgumentException(
                    $"The root fillet (rho_f = {fillet:0.####}) reaches the pitch circle, leaving no "
                    + "hypocycloidal flank. Reduce the fillet coefficient.", nameof(spec));
            filletCentre = filletFlankPoint + FilletNormal(r, rho, theta0, tLow) * fillet;
            filletRootPoint = filletCentre * (rf / filletCentre.Length);
            filletArc = Curve2dChains.ArcBetween(filletCentre, fillet, filletRootPoint, filletFlankPoint);
            filletSweep = filletArc.SweepAngle;
        }

        // Tip arc: the face's own polar angle at the tip decides the half thickness there, and
        // a tip THICKNESS below the weld tier (a LENGTH - angular epsilons scale with radius)
        // is a pointed tooth, refused by name.
        var tipPoint = Face(tTip);
        double tipHalfAngle = -Math.Atan2(tipPoint.Y, tipPoint.X);
        double tipThickness = 2 * tipHalfAngle * ra;
        if (tipThickness < 1e-9)
            throw new ArgumentException(
                $"The tooth comes to a point: tip thickness {tipThickness:0.###e0} at addendum "
                + $"{spec.AddendumCoefficient}*m. Reduce the addendum or add teeth.", nameof(spec));

        // ---- canonical right side, root -> tip ----
        var right = new List<Curve2d>();
        if (filletArc is not null)
            right.Add(filletArc);
        var flankChain = Curve2dChains.Fit(Flank, FlankT, 0, tLow, tolerance, out double flankDeviation);
        for (int i = flankChain.Count - 1; i >= 0; i--)
            right.Add(Curve2dChains.Reverse(flankChain[i]));
        var faceChain = Curve2dChains.Fit(Face, FaceT, 0, tTip, tolerance, out double faceDeviation);
        right.AddRange(faceChain);

        var tipArc = new Arc2d(Vector2d.Zero, ra, -tipHalfAngle, 2 * tipHalfAngle);

        // Left side: the exact mirror of the right side across +X, traversed tip -> root
        // (an arithmetic mirror, never a second fit).
        var left = new List<Curve2d>(right.Count);
        for (int i = right.Count - 1; i >= 0; i--)
            left.Add(Curve2dChains.Reverse(Curve2dChains.MirrorX(right[i])));

        var rootPoint = filletArc is not null ? filletRootPoint : Flank(tRoot);
        double rootPointAngle = -Math.Atan2(rootPoint.Y, rootPoint.X);
        double pitchAngle = 2 * Math.PI / z;
        double rootSweep = pitchAngle - 2 * rootPointAngle;
        double rootLength = rootSweep * rf;
        if (rootLength < -1e-9)
            throw new ArgumentException(
                $"The root fillet (rho_f = {spec.RootFilletCoefficient}*m = {fillet:0.####}) does not "
                + $"fit the root gap: adjacent flanks overlap by {-rootSweep:0.####} rad at the root "
                + "circle. Reduce the fillet coefficient or the dedendum, or add teeth.", nameof(spec));
        Arc2d? rootArc = rootLength < 1e-9 ? null : new Arc2d(Vector2d.Zero, rf, rootPointAngle, rootSweep);

        // ---- assemble every tooth by exact parameter rotation ----
        var tooth = new List<Curve2d>(right.Count + left.Count + 2);
        tooth.AddRange(right);
        tooth.Add(tipArc);
        tooth.AddRange(left);
        if (rootArc is not null)
            tooth.Add(rootArc);

        var outline = new List<Curve2d>(tooth.Count * z);
        for (int k = 0; k < z; k++)
        {
            double beta = k * pitchAngle;
            double cos = Math.Cos(beta), sin = Math.Sin(beta);
            foreach (var piece in tooth)
                outline.Add(Curve2dChains.Rotate(piece, cos, sin, beta));
        }
        var sketch = Sketch.FromCurves(outline);

        // Exact area of the ideal outline by Green's theorem. Both cycloid families give
        // x·dy - y·dx = (const)·(1 - cos(r·t/rho)) - the epicycloid with (r+rho)(r+2rho) and
        // the hypocycloid with (r-rho)(r-2rho) - and the flank's is NEGATED because the flank
        // is the reflected roll and is traversed root -> tip.
        double faceTerm = 0.5 * (r + rho) * (r + 2 * rho) * (tTip - (rho / r) * Math.Sin(r * tTip / rho));
        double flankTerm = 0.5 * (r - rho) * (r - 2 * rho) * (tLow - (rho / r) * Math.Sin(r * tLow / rho));
        double filletTerm = filletArc is not null
            ? 0.5 * (filletCentre.Cross(filletFlankPoint - filletRootPoint) + fillet * fillet * filletSweep)
            : 0;
        double areaPerTooth =
            2 * (filletTerm + flankTerm + faceTerm)
            + 0.5 * ra * ra * tipArc.SweepAngle
            + (rootArc is not null ? 0.5 * rf * rf * rootSweep : 0);

        var geometry = new CycloidalToothGeometry(
            r, rho, ra, rf, fillet, psi, theta0, tTip, tLow, tipArc.SweepAngle, rootArc?.SweepAngle ?? 0);
        return new CycloidalProfile(spec, sketch, tolerance,
            Math.Max(faceDeviation, flankDeviation), faceChain.Count, flankChain.Count,
            z * areaPerTooth, geometry);
    }

    /// <summary>
    /// A cycloidal spur gear solid: the <see cref="Spur"/> profile extruded to
    /// <paramref name="faceWidth"/>, with an optional plain bore. Exact in all three
    /// representations (the profile is lines and circular arcs).
    /// </summary>
    public static Shape SpurGear(CycloidalGearSpec spec, double faceWidth, double boreDiameter = 0,
        double? fitTolerance = null)
    {
        ArgumentNullException.ThrowIfNull(spec);
        if (!(faceWidth > 0))
            throw new ArgumentOutOfRangeException(nameof(faceWidth));
        var profile = Spur(spec, fitTolerance);
        var sketch = profile.Sketch;
        if (boreDiameter > 0)
        {
            if (boreDiameter >= spec.RootDiameter)
                throw new ArgumentOutOfRangeException(nameof(boreDiameter),
                    $"Bore diameter {boreDiameter:0.###} reaches the root circle "
                    + $"(diameter {spec.RootDiameter:0.###}).");
            sketch = sketch.WithHole(Sketch.Circle(boreDiameter / 2));
        }
        return Shape.Extrude(sketch, faceWidth);
    }

    // ------------------------------------------------------------------ cycloid math

    /// <summary>
    /// Epicycloid of the pitch circle: a point on a circle of radius <paramref name="rho"/>
    /// rolling OUTSIDE it, anchored on the ray <paramref name="theta0"/> at roll
    /// <paramref name="t"/> and curling counter-clockwise. Written as r + (a term exactly zero
    /// at t = 0) so the cusp lands on the pitch point EXACTLY — which is what lets the face
    /// and the flank hand over their shared point bit for bit.
    /// </summary>
    private static Vector2d FacePoint(double r, double rho, double theta0, double t)
    {
        double k = (r + rho) / rho;
        double half = Math.Sin(t / 2), halfK = Math.Sin(k * t / 2);
        double x = r - 2 * ((r + rho) * half * half - rho * halfK * halfK);
        double y = (r + rho) * Math.Sin(t) - rho * Math.Sin(k * t);
        return Curve2dChains.RotatePoint(x, y, theta0);
    }

    /// <summary>
    /// Unit tangent of <see cref="FacePoint"/>, exact and defined AT the cusp. The half-angle
    /// form P'(t) = 2(r+ρ)·sin(rt/2ρ)·(cos, sin)((r+2ρ)t/2ρ) factors the vanishing speed out
    /// as a positive scalar, leaving a direction that is radial at t = 0.
    /// </summary>
    private static Vector2d FaceTangent(double r, double rho, double theta0, double t)
    {
        double a = (r + 2 * rho) * t / (2 * rho);
        return Curve2dChains.RotatePoint(Math.Cos(a), Math.Sin(a), theta0);
    }

    /// <summary>
    /// Hypocycloid of the pitch circle in the FLANK sense: the rolling circle turns the other
    /// way, so the tooth WIDENS below the pitch circle (which is what a cycloidal tooth does)
    /// rather than necking. At ρ = r/2 every point has y ≡ 0 and the curve is the straight
    /// radial line — reached by the arithmetic, not by a special case.
    /// </summary>
    private static Vector2d FlankPoint(double r, double rho, double theta0, double t)
    {
        double k = (r - rho) / rho;
        double half = Math.Sin(t / 2), halfK = Math.Sin(k * t / 2);
        double x = r - 2 * ((r - rho) * half * half + rho * halfK * halfK);
        double y = rho * Math.Sin(k * t) - (r - rho) * Math.Sin(t);
        return Curve2dChains.RotatePoint(x, y, theta0);
    }

    /// <summary>Unit tangent of <see cref="FlankPoint"/> (radially inward at the cusp), exact
    /// from the same half-angle factorization: (−cos(βt), −sin(βt)) with β = (r−2ρ)/2ρ, which
    /// is the CONSTANT (−1, 0) exactly when the flank is radial.</summary>
    private static Vector2d FlankTangent(double r, double rho, double theta0, double t)
    {
        double b = (r - 2 * rho) * t / (2 * rho);
        return Curve2dChains.RotatePoint(-Math.Cos(b), -Math.Sin(b), theta0);
    }

    /// <summary>The flank's gap-side unit normal (the left normal of the inward-running
    /// tangent) — the direction a root fillet's centre lies from its tangency point.</summary>
    private static Vector2d FilletNormal(double r, double rho, double theta0, double t)
    {
        var tangent = FlankTangent(r, rho, theta0, t);
        return new Vector2d(-tangent.Y, tangent.X);
    }

    private static double Clamp(double value) => value < -1 ? -1 : value > 1 ? 1 : value;
}

/// <summary>
/// Clock and instrument gear proportions from <b>BS 978-2</b> (fine pitch gears — cycloidal
/// type for instruments and clockwork).
/// </summary>
/// <remarks>
/// <para>
/// ⚠ <b>TRANSCRIBED — verify against the current standard before production use.</b> These
/// rows carry the same warning as <c>StandardHoles</c>' Tappex table: they are typed from a
/// reference, and a test asserting them verifies the typing, not the standard.
/// </para>
/// <para>
/// Only the ADDENDUM columns are transcribed. The dedendum is DERIVED rather than stored a
/// second time — a member's dedendum has to clear its mate's addendum, so it is the mate's
/// addendum plus a clearance, and a second stored column could only drift from that (the
/// fine-pitch tap-drill rule). The distinctive content of the standard is that the wheel's
/// addendum grows as the pinion gets smaller: a low-leaf pinion needs a taller wheel tooth to
/// keep the arc of recess long enough to carry the drive past the line of centres.
/// </para>
/// </remarks>
public static class ClockGearProportions
{
    // ⚠ VERIFY AGAINST DATASHEET. pinion leaves -> (wheel addendum, pinion addendum), of module.
    private static readonly (int Leaves, double Wheel, double Pinion)[] Table =
    [
        (6,  0.855, 0.855),
        (7,  0.670, 0.855),
        (8,  0.625, 0.670),
        (9,  0.580, 0.670),
        (10, 0.545, 0.670),
        (11, 0.525, 0.625),
        (12, 0.510, 0.625),
    ];

    /// <summary>The smallest pinion leaf count the table covers.</summary>
    public static int MinimumLeaves => Table[0].Leaves;

    /// <summary>Leaf counts past this take the last row (the table is flat from there on).</summary>
    public static int MaximumTabulatedLeaves => Table[^1].Leaves;

    /// <summary>Wheel addendum coefficient (of module) for a wheel driven by / driving a pinion
    /// of <paramref name="pinionLeaves"/> leaves. ⚠ transcribed — verify against BS 978-2.</summary>
    public static double WheelAddendumCoefficient(int pinionLeaves) => Row(pinionLeaves).Wheel;

    /// <summary>Pinion addendum coefficient (of module) for a pinion of
    /// <paramref name="pinionLeaves"/> leaves. ⚠ transcribed — verify against BS 978-2.</summary>
    public static double PinionAddendumCoefficient(int pinionLeaves) => Row(pinionLeaves).Pinion;

    /// <summary>
    /// A conjugate clock pair on the BS 978-2 proportions: one describing circle of half the
    /// pinion's pitch diameter (so the pinion's leaves are radial), the tabulated addenda, and
    /// each member's dedendum DERIVED as its mate's addendum plus
    /// <paramref name="clearanceCoefficient"/>·m.
    /// </summary>
    public static CycloidalMesh Bs978Part2(double module, int pinionLeaves, int wheelTeeth,
        double clearanceCoefficient = 0.05)
    {
        if (!(clearanceCoefficient >= 0))
            throw new ArgumentOutOfRangeException(nameof(clearanceCoefficient));
        var row = Row(pinionLeaves);
        var mesh = CycloidalGears.Pair(module, pinionLeaves, wheelTeeth);
        return new CycloidalMesh(
            mesh.Pinion with
            {
                AddendumCoefficient = row.Pinion,
                DedendumCoefficient = row.Wheel + clearanceCoefficient,
            },
            mesh.Wheel with
            {
                AddendumCoefficient = row.Wheel,
                DedendumCoefficient = row.Pinion + clearanceCoefficient,
            });
    }

    private static (int Leaves, double Wheel, double Pinion) Row(int pinionLeaves)
    {
        if (pinionLeaves < MinimumLeaves)
            throw new ArgumentOutOfRangeException(nameof(pinionLeaves),
                $"BS 978-2 tabulates cycloidal pinions from {MinimumLeaves} leaves; "
                + $"{pinionLeaves} is below the table and this factory will not extrapolate one.");
        foreach (var row in Table)
            if (row.Leaves == pinionLeaves)
                return row;
        return Table[^1];   // the table is flat past its last tabulated leaf count
    }
}
