using EngrCAD.BRep;
using EngrCAD.Core;
using EngrCAD.Implicit;
using EngrCAD.Modeling;
using Xunit;

namespace EngrCAD.Modeling.Tests;

public class CycloidalGearTests
{
    // ---- the identities, as arithmetic ----

    [Fact]
    public void SpecIdentities_HoldAsArithmetic()
    {
        var spec = new CycloidalGearSpec(module: 2, teeth: 24, generatingCircleDiameter: 10);

        Assert.Equal(48, spec.PitchDiameter, 12);
        Assert.Equal(24, spec.PitchRadius, 12);
        Assert.Equal(2 * Math.PI, spec.CircularPitch, 12);
        Assert.Equal(5, spec.GeneratingCircleRadius, 12);

        // An epicycloid of a rolling circle of radius rho reaches r + 2*rho and no further,
        // and a hypocycloid reaches |r - 2*rho| - the two limits the addendum and the
        // dedendum are refused against.
        Assert.Equal(10, spec.MaximumAddendum, 12);
        Assert.Equal(Math.Abs(24 - 10), spec.DeepestFlankRadius, 12);

        // The radial-flank identity is rho = r/2, i.e. a describing circle whose DIAMETER
        // equals the pitch radius.
        Assert.Equal(spec.PitchRadius, spec.RadialFlankGeneratingDiameter, 12);
        Assert.False(spec.HasRadialFlanks);
        Assert.True(CycloidalGearSpec.WithRadialFlanks(2, 24).HasRadialFlanks);
        Assert.Equal(spec.PitchRadius / 2,
            CycloidalGearSpec.WithRadialFlanks(2, 24).GeneratingCircleRadius, 12);

        // Backlash comes off the tooth thickness at the pitch circle, half from each flank.
        var thinned = spec with { BacklashAllowance = 0.08 };
        Assert.Equal(Math.PI - 0.08, thinned.ToothThicknessAtPitch, 12);
        Assert.Equal((Math.PI - 0.08) / (2 * 24), thinned.HalfToothAngle, 12);
    }

    [Fact]
    public void Pair_TakesTheClassicClockDescribingCircle()
    {
        // Half the PINION's pitch diameter, so the pinion's leaves are radial and the wheel's
        // flanks are not - the asymmetry is the point.
        var mesh = CycloidalGears.Pair(module: 1, pinionTeeth: 10, wheelTeeth: 40);
        Assert.Equal(5, mesh.GeneratingCircleDiameter, 12);
        Assert.True(mesh.Pinion.HasRadialFlanks);
        Assert.False(mesh.Wheel.HasRadialFlanks);
        Assert.Equal(25, mesh.CentreDistance, 12);
        Assert.Equal(4, mesh.GearRatio, 12);
    }

    // ---- the radial-flank identity, MEASURED off the generated sketch ----
    //
    // A hypocycloid generated by a circle of half the pitch radius is a straight line through
    // the gear centre. Nothing in the factory special-cases that: the general cycloid formula
    // and the general biarc fit reach it on their own, which is exactly why measuring it off
    // the OUTPUT is a test rather than a restatement. The measurement asks the sketch's own
    // exact signed distance where the boundary crosses a circle of a given radius, and a
    // radial flank puts every one of those crossings on the same ray.

    [Fact]
    public void RadialFlanks_MeasureStraightOffTheGeneratedSketch()
    {
        var spec = CycloidalGearSpec.WithRadialFlanks(module: 1, teeth: 12);
        var profile = CycloidalGears.Spur(spec);
        double drift = FlankAngularDrift(profile, out double psi);

        // The exact-line case: the crossings sit on the ray at -psi to round-off, and the
        // fit produced literal straight segments (2 collinear halves of one biarc).
        Assert.True(drift < 1e-12, $"radial flank drifted {drift:0.###e0} rad from the ray at -{psi}");
        Assert.Equal(2, profile.CurvesPerFlank);
        Assert.All(FirstFlankPieces(profile), piece => Assert.IsType<Line2d>(piece));
    }

    [Fact]
    public void NonRadialFlanks_DriftMeasurably_SoTheInstrumentCanSeeAFlank()
    {
        // The same measurement on a gear cut by the same describing circle but with four times
        // the teeth: its flanks are hypocycloids, not lines, and the tooth WIDENS toward the
        // root (the flank leans away from the tooth centre going in).
        var mesh = CycloidalGears.Pair(module: 1, pinionTeeth: 12, wheelTeeth: 48);
        var wheel = CycloidalGears.Spur(mesh.Wheel);
        double drift = FlankAngularDrift(wheel, out _);
        Assert.True(drift > 1e-3,
            $"a hypocycloidal flank should drift measurably off the radial ray; measured {drift:0.###e0} rad");

        // Direction: the crossing angle at the root is FURTHER from the tooth centre than at
        // the pitch circle, i.e. the tooth is thicker at the root.
        var region = wheel.Sketch.ToRegion();
        double r = mesh.Wheel.PitchRadius;
        double rf = mesh.Wheel.RootDiameter / 2;
        double psi = mesh.Wheel.HalfToothAngle;
        double atPitch = -RightFlankCrossing(region, r - 1e-6, psi);
        double atRoot = -RightFlankCrossing(region, rf + 0.02, psi);
        Assert.True(atRoot > atPitch,
            $"the flank should lean away from the tooth centre going inward: {atRoot} vs {atPitch}");
    }

    [Fact]
    public void ToothThicknessAtThePitchCircle_MeasuresTheSpec()
    {
        foreach (double backlash in new[] { 0.0, 0.05 })
        {
            var spec = new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12)
            { BacklashAllowance = backlash };
            var profile = CycloidalGears.Spur(spec);
            var region = profile.Sketch.ToRegion();
            double r = spec.PitchRadius;
            double psi = spec.HalfToothAngle;
            // Probe just inside the pitch circle so both flanks are genuine boundary crossings.
            double right = RightFlankCrossing(region, r - 1e-7, psi);
            double left = LeftFlankCrossing(region, r - 1e-7, psi);
            double measured = (left - right) * r;
            Assert.True(Math.Abs(measured - spec.ToothThicknessAtPitch) < 1e-5,
                $"tooth thickness measured {measured} against {spec.ToothThicknessAtPitch} "
                + $"(backlash {backlash})");
        }
    }

    // ---- the fit contract ----

    [Fact]
    public void FitDeviation_HonorsItsStatedTolerance()
    {
        var spec = new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12);
        var loose = CycloidalGears.Spur(spec, fitTolerance: 2e-3);
        var tight = CycloidalGears.Spur(spec, fitTolerance: 2e-6);
        Assert.True(loose.MaxFitDeviation <= loose.FitTolerance,
            $"{loose.MaxFitDeviation} exceeds {loose.FitTolerance}");
        Assert.True(tight.MaxFitDeviation <= tight.FitTolerance,
            $"{tight.MaxFitDeviation} exceeds {tight.FitTolerance}");
        // A tighter tolerance genuinely buys arcs (so the reported deviation is not a constant
        // the fit reaches whatever it is asked for).
        Assert.True(tight.CurvesPerFace > loose.CurvesPerFace);
        Assert.True(tight.MaxFitDeviation < loose.MaxFitDeviation);
        // The default is module * 1e-4.
        Assert.Equal(2e-4, CycloidalGears.Spur(spec).FitTolerance, 15);
    }

    [Fact]
    public void ClosedFormArea_MatchesTheGeneratedSketch()
    {
        // Both cycloid families integrate in closed form under Green's theorem, so the profile
        // states an EXACT area for the ideal outline; the sketch's own area may differ only by
        // the fit deviation spread over the fitted length.
        foreach (var spec in new[]
        {
            CycloidalGearSpec.WithRadialFlanks(module: 1, teeth: 12),
            new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12),
            new CycloidalGearSpec(module: 1, teeth: 48, generatingCircleDiameter: 5),
            new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12)
                { RootFilletCoefficient = 0 },
        })
        {
            var profile = CycloidalGears.Spur(spec);
            double measured = profile.Sketch.Area();
            double bound = profile.MaxFitDeviation * FittedLength(profile) * 2 + 1e-9;
            Assert.True(Math.Abs(measured - profile.ClosedFormArea) < bound,
                $"z={spec.Teeth}: sketch area {measured} vs closed form {profile.ClosedFormArea} "
                + $"(bound {bound})");
        }
    }

    [Fact]
    public void RadialFlank_ContributesExactlyNothingToTheClosedFormArea()
    {
        // The hypocycloid's Green term carries the factor (r - 2*rho), which is exactly zero at
        // the radial-flank identity - a line through the origin encloses nothing. Building the
        // same gear with a slightly smaller describing circle must move the area.
        var radial = CycloidalGears.Spur(CycloidalGearSpec.WithRadialFlanks(1, 12));
        var curved = CycloidalGears.Spur(new CycloidalGearSpec(1, 12, generatingCircleDiameter: 5.0));
        Assert.True(Math.Abs(radial.ClosedFormArea - curved.ClosedFormArea) > 1e-3,
            "a different describing circle must change the enclosed area");
    }

    // ---- conjugate action, from CONTACT at the DESIGN centre distance ----
    //
    // Cycloidal conjugacy is a property of the PAIR: one describing circle traces the wheel's
    // epicycloidal face and the pinion's hypocycloidal flank, so sharing it is the law of
    // gearing. Unlike an involute pair, the ratio is constant only at the design centre
    // distance (the describing circle has to roll on BOTH pitch circles), so the measurement
    // is made there and backlash comes from THINNING the teeth instead - which is exact,
    // because rotating a cycloid about its own pitch circle's centre is the same cycloid at
    // another phase.
    //
    // The mechanism solver is deliberately not the instrument: Coupling.Gear ENFORCES a ratio.
    // Contact through the sketch's exact signed distance derives it from the drawn teeth.

    private const double ConjugacySweepPitches = 1.2;

    [Fact]
    public void ConjugateAction_RatioConstantThroughToothHandover()
    {
        var mesh = CycloidalGears.Pair(module: 1, pinionTeeth: 10, wheelTeeth: 30);
        double spread = ContactSpread(WithBacklash(mesh.Pinion), WithBacklash(mesh.Wheel),
            extraCentreDistance: 0, sweepPitches: ConjugacySweepPitches, samples: 8);
        // Tolerance derivation: each flank deviates <= its fit tolerance (1e-4) from the true
        // cycloid, boundary sampling at 0.02 mm under a relative contact curvature radius of a
        // few mm adds ~1e-5, and the pinion's base radius for the angular conversion is 5 mm -
        // so ~4e-5 rad of position uncertainty. Asserted at 2e-4 (5x headroom); measured 4e-6.
        Assert.True(spread < 2e-4, $"transmission varied by {spread:0.###e0} rad across the sweep");
    }

    [Fact]
    public void ConjugateAction_WrongDescribingCircle_IsSeenByTheSameInstrument()
    {
        // The mutation: a wheel cut with a describing circle the pinion was not cut with. Both
        // gears are still perfectly good cycloidal gears; only the PAIRING is broken, which is
        // precisely the failure a ratio-only check cannot see.
        var mesh = CycloidalGears.Pair(module: 1, pinionTeeth: 10, wheelTeeth: 30);
        var wrongWheel = new CycloidalGearSpec(1, 30, mesh.GeneratingCircleDiameter * 1.6);
        double conjugate = ContactSpread(WithBacklash(mesh.Pinion), WithBacklash(mesh.Wheel),
            0, 0.6, 6);
        double mutated = ContactSpread(WithBacklash(mesh.Pinion), WithBacklash(wrongWheel),
            0, 0.6, 6);
        Assert.True(mutated > 50 * conjugate,
            $"a wrong describing circle read {mutated:0.###e0} rad against the conjugate pair's "
            + $"{conjugate:0.###e0} - the instrument cannot see flank FORM");
    }

    [Fact]
    public void CentreDistanceError_RipplesTheRatio_TheHonestContrastWithTheInvolute()
    {
        // NOT a defect: an involute pair is centre-distance invariant because its ratio is set
        // by the base circles, while a cycloidal pair's describing circle must roll on both
        // pitch circles at once. Mounted long, the pair still runs and the ratio ripples. The
        // sensitivity is measured here so the docs can state a number instead of a warning.
        var mesh = CycloidalGears.Pair(module: 1, pinionTeeth: 10, wheelTeeth: 30);
        var pinion = WithBacklash(mesh.Pinion);
        var wheel = WithBacklash(mesh.Wheel);
        double atDesign = ContactSpread(pinion, wheel, 0, 0.6, 6);
        double mountedLong = ContactSpread(pinion, wheel, 0.3, 0.6, 6);
        Assert.True(mountedLong > 50 * atDesign,
            $"0.3 mm of centre-distance error read {mountedLong:0.###e0} rad against "
            + $"{atDesign:0.###e0} at the design distance");
    }

    // ---- refusals, by name ----

    [Fact]
    public void DescribingCirclePastHalfThePitchRadius_RefusedAsUndercut()
    {
        var ex = Assert.Throws<ArgumentException>(() =>
            CycloidalGears.Spur(new CycloidalGearSpec(1, 12, generatingCircleDiameter: 7)));
        Assert.Contains("undercut", ex.Message);
    }

    [Fact]
    public void AddendumPastTheEpicycloidsReach_Refused()
    {
        // A tiny describing circle traces a short epicycloid: rho = 0.25 reaches only 0.5 above
        // the pitch circle, so a 0.6 m addendum has no face to draw.
        var ex = Assert.Throws<ArgumentException>(() =>
            CycloidalGears.Spur(new CycloidalGearSpec(1, 20, generatingCircleDiameter: 0.5)));
        Assert.Contains("epicycloid", ex.Message);
    }

    [Fact]
    public void DedendumPastTheHypocycloidsReach_Refused()
    {
        var ex = Assert.Throws<ArgumentException>(() =>
            CycloidalGears.Spur(new CycloidalGearSpec(1, 20, generatingCircleDiameter: 1.2)
                { AddendumCoefficient = 0.5, DedendumCoefficient = 9.0 }));
        Assert.Contains("hypocycloid", ex.Message);
    }

    [Fact]
    public void PointedTooth_Refused()
    {
        var ex = Assert.Throws<ArgumentException>(() =>
            CycloidalGears.Spur(new CycloidalGearSpec(1, 6, generatingCircleDiameter: 3)
                { AddendumCoefficient = 1.4 }));
        Assert.Contains("point", ex.Message);
    }

    [Fact]
    public void OversizedRootFillet_Refused()
    {
        var ex = Assert.Throws<ArgumentException>(() =>
            CycloidalGears.Spur(new CycloidalGearSpec(1, 20, generatingCircleDiameter: 10)
                { RootFilletCoefficient = 3.0 }));
        Assert.Contains("fillet", ex.Message);
    }

    [Fact]
    public void MeshRefusesGearsThatDoNotShareADescribingCircle()
    {
        var pinion = new CycloidalGearSpec(1, 10, 5);
        var wheel = new CycloidalGearSpec(1, 30, 6);
        var ex = Assert.Throws<ArgumentException>(() => CycloidalGears.Mesh(pinion, wheel));
        Assert.Contains("describing circle", ex.Message);

        var wrongModule = new CycloidalGearSpec(2, 30, 5);
        Assert.Contains("module",
            Assert.Throws<ArgumentException>(() => CycloidalGears.Mesh(pinion, wrongModule)).Message);

        // The conjugate pair passes.
        var mesh = CycloidalGears.Pair(1, 10, 30);
        Assert.Equal(5, CycloidalGears.Mesh(mesh.Pinion, mesh.Wheel).GeneratingCircleDiameter, 12);
    }

    // ---- BS 978-2 transcription ----

    [Fact]
    public void Bs978Part2_RowsAreAsTranscribed()
    {
        // A transcription test verifies the TYPING, not the standard - the table carries the
        // verify-against-datasheet flag for the physics.
        Assert.Equal(0.855, ClockGearProportions.WheelAddendumCoefficient(6), 12);
        Assert.Equal(0.670, ClockGearProportions.WheelAddendumCoefficient(7), 12);
        Assert.Equal(0.625, ClockGearProportions.WheelAddendumCoefficient(8), 12);
        Assert.Equal(0.580, ClockGearProportions.WheelAddendumCoefficient(9), 12);
        Assert.Equal(0.545, ClockGearProportions.WheelAddendumCoefficient(10), 12);
        Assert.Equal(0.525, ClockGearProportions.WheelAddendumCoefficient(11), 12);
        Assert.Equal(0.510, ClockGearProportions.WheelAddendumCoefficient(12), 12);
        Assert.Equal(0.855, ClockGearProportions.PinionAddendumCoefficient(6), 12);
        Assert.Equal(0.625, ClockGearProportions.PinionAddendumCoefficient(11), 12);

        // Structure the numbers must have whatever the digits are: the wheel's addendum grows
        // strictly as the pinion shrinks, and the table is flat past its last row.
        for (int leaves = 6; leaves < 12; leaves++)
            Assert.True(ClockGearProportions.WheelAddendumCoefficient(leaves)
                > ClockGearProportions.WheelAddendumCoefficient(leaves + 1),
                $"the wheel addendum should fall with rising leaf count at {leaves}");
        Assert.Equal(ClockGearProportions.WheelAddendumCoefficient(12),
            ClockGearProportions.WheelAddendumCoefficient(40), 12);

        Assert.Contains("6 leaves",
            Assert.Throws<ArgumentOutOfRangeException>(
                () => ClockGearProportions.WheelAddendumCoefficient(5)).Message);
    }

    [Fact]
    public void Bs978Part2_DerivesEachDedendumFromItsMatesAddendum()
    {
        var mesh = ClockGearProportions.Bs978Part2(module: 0.5, pinionLeaves: 8, wheelTeeth: 60);
        Assert.True(mesh.Pinion.HasRadialFlanks);
        Assert.Equal(ClockGearProportions.PinionAddendumCoefficient(8), mesh.Pinion.AddendumCoefficient, 12);
        Assert.Equal(ClockGearProportions.WheelAddendumCoefficient(8), mesh.Wheel.AddendumCoefficient, 12);
        // A member's dedendum clears its MATE's addendum plus the clearance - derived, never a
        // second stored column that could drift.
        Assert.Equal(mesh.Wheel.AddendumCoefficient + 0.05, mesh.Pinion.DedendumCoefficient, 12);
        Assert.Equal(mesh.Pinion.AddendumCoefficient + 0.05, mesh.Wheel.DedendumCoefficient, 12);
        // And both members generate.
        Assert.True(CycloidalGears.Spur(mesh.Pinion).Sketch.Area() > 0);
        Assert.True(CycloidalGears.Spur(mesh.Wheel).Sketch.Area() > 0);
    }

    // ---- solids ----

    [Fact]
    public void SpurGear_MeshVolume_MatchesAreaTimesWidth()
    {
        var spec = new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12);
        var profile = CycloidalGears.Spur(spec);
        var shape = CycloidalGears.SpurGear(spec, faceWidth: 8, boreDiameter: 10);
        var mesh = shape.ToMesh();
        Assert.True(mesh.IsClosed);
        double expected = (profile.ClosedFormArea - Math.PI * 25) * 8;
        double relative = Math.Abs(mesh.Volume() - expected) / expected;
        // Inscribed-chord tessellation of the arcs: relative deficit ~ (2*pi/64)^2/6 ~ 1.6e-3.
        Assert.True(relative < 0.01, $"volume {mesh.Volume()} vs {expected} ({relative:0.###e0} relative)");
    }

    [Fact]
    public void Bore_ReachingTheRootCircle_Refused()
    {
        var spec = new CycloidalGearSpec(module: 2, teeth: 20, generatingCircleDiameter: 12);
        Assert.Throws<ArgumentOutOfRangeException>(() =>
            CycloidalGears.SpurGear(spec, faceWidth: 8, boreDiameter: spec.RootDiameter));
    }

    // ------------------------------------------------------------------ helpers

    private static CycloidalGearSpec WithBacklash(CycloidalGearSpec spec) =>
        spec with { BacklashAllowance = 0.03 };

    /// <summary>The greatest angular drift of the right flank's boundary crossings off the
    /// radial ray at −ψ, measured over radii spanning the flank.</summary>
    private static double FlankAngularDrift(CycloidalProfile profile, out double psi)
    {
        var region = profile.Sketch.ToRegion();
        double r = profile.Spec.PitchRadius;
        double rf = profile.Spec.RootDiameter / 2;
        psi = profile.Spec.HalfToothAngle;
        // Stay clear of the root fillet, which is an arc by design and not part of the flank.
        double low = rf + 0.35 * (r - rf);
        double worst = 0;
        for (int i = 0; i <= 12; i++)
        {
            double radius = low + (r - 1e-7 - low) * i / 12;
            worst = Math.Max(worst, Math.Abs(RightFlankCrossing(region, radius, psi) + psi));
        }
        return worst;
    }

    private static IEnumerable<Curve2d> FirstFlankPieces(CycloidalProfile profile)
    {
        // The canonical tooth is: root fillet, flank chain, face chain, tip arc, ... - so the
        // flank pieces follow the single fillet arc.
        var curves = profile.Sketch.ToCurves();
        return curves.Skip(1).Take(profile.CurvesPerFlank);
    }

    /// <summary>Bisects the outline crossing along the circle of radius <paramref name="radius"/>
    /// between the tooth centre (inside) and the gap at −(ψ + a pitch fraction) (outside).</summary>
    private static double RightFlankCrossing(IPlanarRegion region, double radius, double psi)
        => BisectCrossing(region, radius, 0, -(psi + 0.35 * psi + 0.02 / Math.Max(radius, 1e-9)));

    private static double LeftFlankCrossing(IPlanarRegion region, double radius, double psi)
        => BisectCrossing(region, radius, 0, psi + 0.35 * psi + 0.02 / Math.Max(radius, 1e-9));

    private static double BisectCrossing(IPlanarRegion region, double r, double inside, double outside)
    {
        double At(double theta) => region.SignedDistance(new Vector2d(r * Math.Cos(theta), r * Math.Sin(theta)));
        Assert.True(At(inside) < 0, "inside probe is not inside");
        Assert.True(At(outside) > 0, "outside probe is not outside");
        for (int i = 0; i < 60; i++)
        {
            double mid = (inside + outside) / 2;
            if (At(mid) < 0) inside = mid; else outside = mid;
        }
        return (inside + outside) / 2;
    }

    /// <summary>Total fitted (cycloidal) length in the outline — the length the fit deviation
    /// can act over when the sketch's area is compared against the closed form.</summary>
    private static double FittedLength(CycloidalProfile profile)
    {
        double r = profile.Spec.PitchRadius;
        double span = profile.Spec.TipDiameter / 2 - profile.Spec.RootDiameter / 2;
        return 2 * profile.Spec.Teeth * span * 1.6 + r;   // generous: chords are shorter than this
    }

    /// <summary>
    /// The spread of the drive-flank contact offset β* over a sweep of pinion angles: the wheel
    /// is rotated toward contact and the touching angle found by bisection of the clearance —
    /// the minimum of the pinion region's exact signed distance over the wheel outline's
    /// sampled points. A constant β* IS constant transmission.
    /// </summary>
    private static double ContactSpread(CycloidalGearSpec pinionSpec, CycloidalGearSpec wheelSpec,
        double extraCentreDistance, double sweepPitches, int samples)
    {
        var pinion = CycloidalGears.Spur(pinionSpec);
        var wheel = CycloidalGears.Spur(wheelSpec);
        var region = pinion.Sketch.ToRegion();
        double a = (pinionSpec.PitchDiameter + wheelSpec.PitchDiameter) / 2 + extraCentreDistance;
        double ratio = (double)pinionSpec.Teeth / wheelSpec.Teeth;
        double wheelPitch = 2 * Math.PI / wheelSpec.Teeth;
        double alignment = Math.PI - wheelPitch / 2;   // a wheel gap on the line of centres
        double tipRadius = pinionSpec.TipDiameter / 2 + 0.05;
        double sweepRange = sweepPitches * 2 * Math.PI / pinionSpec.Teeth;

        var points = new List<Vector2d>();
        foreach (var curve in wheel.Sketch.ToCurves())
        {
            double length = Curve2dLength(curve);
            int n = Math.Max(2, (int)Math.Ceiling(length / 0.02));
            for (int i = 0; i < n; i++)
                points.Add(curve.PointAt((double)i / n));
        }

        double Clearance(double phi1, double phi2)
        {
            double c1 = Math.Cos(-phi1), s1 = Math.Sin(-phi1);
            double c2 = Math.Cos(phi2), s2 = Math.Sin(phi2);
            double min = 1.0;
            foreach (var p in points)
            {
                double wx = a + p.X * c2 - p.Y * s2;
                double wy = p.X * s2 + p.Y * c2;
                if (wx * wx + wy * wy > tipRadius * tipRadius)
                    continue;
                var q = new Vector2d(wx * c1 - wy * s1, wx * s1 + wy * c1);
                min = Math.Min(min, region.SignedDistance(q));
                if (min < -0.05)
                    break;
            }
            return min;
        }

        double lowest = double.PositiveInfinity, highest = double.NegativeInfinity;
        double? previous = null;
        for (int step = 0; step < samples; step++)
        {
            double phi1 = sweepRange * step / (samples - 1);
            double basePhi2 = alignment - ratio * phi1;
            double lo, hi;
            if (previous is double seed
                && Clearance(phi1, basePhi2 + seed - 0.004) > 0
                && Clearance(phi1, basePhi2 + seed + 0.004) < 0)
            {
                lo = seed - 0.004;
                hi = seed + 0.004;
            }
            else
            {
                double bestBeta = double.NaN, bestG = double.NegativeInfinity;
                for (double beta = -0.05; beta <= 0.05; beta += 0.001)
                {
                    double g = Clearance(phi1, basePhi2 + beta);
                    if (g > bestG) { bestG = g; bestBeta = beta; }
                }
                Assert.True(bestG > 0, $"no clearance window found at phi1={phi1}");
                lo = bestBeta;
                hi = bestBeta;
                while (Clearance(phi1, basePhi2 + hi) > 0)
                {
                    lo = hi;
                    hi += 0.002;
                    Assert.True(hi < 0.15, "contact edge not found");
                }
            }
            for (int i = 0; i < 45; i++)
            {
                double mid = (lo + hi) / 2;
                if (Clearance(phi1, basePhi2 + mid) > 0) lo = mid; else hi = mid;
            }
            double contact = (lo + hi) / 2;
            lowest = Math.Min(lowest, contact);
            highest = Math.Max(highest, contact);
            previous = contact;
        }
        return highest - lowest;
    }

    internal static double Curve2dLength(Curve2d curve) => curve switch
    {
        Line2d line => (line.End - line.Start).Length,
        Arc2d arc => arc.Length,
        _ => curve.ArcLength(),
    };
}
