<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EngrCAD.Viewer\EngrCAD.Viewer.csproj" />
    <ProjectReference Include="..\..\src\EngrCAD.Modeling\EngrCAD.Modeling.csproj" />
  </ItemGroup>
</Project>
